/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package College_Inventory_Login;


import Admin_Dashboard.Admin_Dashboard;
import College_Inventory_DB.MySqlConnect;
import User_Dashboard.Dashboard;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Amit Kumar
 */
public class Login extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;    

    /**
     * Creates new form NewSignin
     */
    public Login() {
        initComponents();
        conn=MySqlConnect.ConnecrDb();   
        setIcon();
        this.setLocationRelativeTo(null);
        jPanel6.setVisible(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_UserID = new javax.swing.JTextField();
        ShowPassword = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_info_logo = new javax.swing.JLabel();
        jLabel_info2 = new javax.swing.JLabel();
        jLabel_info1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ForgetConfirmShowPassword = new javax.swing.JToggleButton();
        EnterSecurityAnswer = new javax.swing.JTextField();
        ForgetShowPassword = new javax.swing.JToggleButton();
        confirmnewpassword = new javax.swing.JPasswordField();
        newpassword = new javax.swing.JPasswordField();
        SelectSecurityQuestion = new javax.swing.JComboBox<String>();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        result = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Passerror = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Selecterror = new javax.swing.JLabel();
        Usererror = new javax.swing.JLabel();
        SelectUser = new javax.swing.JComboBox<String>();
        timeshow = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_UserID.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jTextField_UserID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_UserID.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField_UserIDMouseMoved(evt);
            }
        });
        jTextField_UserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_UserIDKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_UserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 260, 40));

        ShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/College_Inventory_Icon/view-1.png"))); // NOI18N
        ShowPassword.setBorder(null);
        ShowPassword.setBorderPainted(false);
        ShowPassword.setContentAreaFilled(false);
        ShowPassword.setFocusPainted(false);
        ShowPassword.setRequestFocusEnabled(false);
        ShowPassword.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/College_Inventory_Icon/hide-1.png"))); // NOI18N
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 40, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_Shield_100px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, 80));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Lock_35px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Male_User_35px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 40));

        jLabel19.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel19.setText("User ID");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 260, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_info_logo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_info_logo.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_info_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_info_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trending.png"))); // NOI18N
        jLabel_info_logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_info_logoMouseClicked(evt);
            }
        });
        jPanel3.add(jLabel_info_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 350, 270));

        jLabel_info2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel_info2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_info2.setText("Stock Management System");
        jPanel3.add(jLabel_info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 350, 60));

        jLabel_info1.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel_info1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_info1.setText("Green Global");
        jPanel3.add(jLabel_info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 350, 190));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trending120.png"))); // NOI18N
        jLabel13.setText("Green Global");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 400, 130));

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Stock Management System");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 250, -1));

        ForgetConfirmShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/College_Inventory_Icon/view-1.png"))); // NOI18N
        ForgetConfirmShowPassword.setBorder(null);
        ForgetConfirmShowPassword.setBorderPainted(false);
        ForgetConfirmShowPassword.setContentAreaFilled(false);
        ForgetConfirmShowPassword.setFocusPainted(false);
        ForgetConfirmShowPassword.setRequestFocusEnabled(false);
        ForgetConfirmShowPassword.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/College_Inventory_Icon/hide-1.png"))); // NOI18N
        ForgetConfirmShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetConfirmShowPasswordActionPerformed(evt);
            }
        });
        jPanel6.add(ForgetConfirmShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 40, 40));

        EnterSecurityAnswer.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        EnterSecurityAnswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EnterSecurityAnswer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                EnterSecurityAnswerMouseMoved(evt);
            }
        });
        jPanel6.add(EnterSecurityAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 350, 40));

        ForgetShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/College_Inventory_Icon/view-1.png"))); // NOI18N
        ForgetShowPassword.setToolTipText("");
        ForgetShowPassword.setBorderPainted(false);
        ForgetShowPassword.setContentAreaFilled(false);
        ForgetShowPassword.setFocusPainted(false);
        ForgetShowPassword.setMaximumSize(new java.awt.Dimension(24, 24));
        ForgetShowPassword.setMinimumSize(new java.awt.Dimension(24, 24));
        ForgetShowPassword.setName(""); // NOI18N
        ForgetShowPassword.setPreferredSize(new java.awt.Dimension(24, 24));
        ForgetShowPassword.setRequestFocusEnabled(false);
        ForgetShowPassword.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/College_Inventory_Icon/hide-1.png"))); // NOI18N
        ForgetShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetShowPasswordActionPerformed(evt);
            }
        });
        jPanel6.add(ForgetShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 40, 40));

        confirmnewpassword.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        confirmnewpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        confirmnewpassword.setMinimumSize(new java.awt.Dimension(2, 23));
        confirmnewpassword.setPreferredSize(new java.awt.Dimension(2, 23));
        confirmnewpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmnewpasswordActionPerformed(evt);
            }
        });
        confirmnewpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmnewpasswordKeyPressed(evt);
            }
        });
        jPanel6.add(confirmnewpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 350, 40));

        newpassword.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        newpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newpassword.setMinimumSize(new java.awt.Dimension(2, 23));
        newpassword.setPreferredSize(new java.awt.Dimension(2, 23));
        newpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newpasswordKeyPressed(evt);
            }
        });
        jPanel6.add(newpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 350, 40));

        SelectSecurityQuestion.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        SelectSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT HERE", "What is the name of your favorite teacher?", "What were the last four digits of your contact number?", "What were the last five digits of your driver's licence number?", "What was the name of the company where you first worked?" }));
        SelectSecurityQuestion.setAutoscrolls(true);
        SelectSecurityQuestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(SelectSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 350, 40));

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel14.setText("Select Security Question");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 20));

        jLabel18.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel18.setText("New Password");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 314, -1));

        jLabel17.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel17.setText("Confirm New Password");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 314, -1));

        jLabel16.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel16.setText("Answer");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 314, -1));

        jButton14.setBackground(new java.awt.Color(169, 224, 49));
        jButton14.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_To_25px.png"))); // NOI18N
        jButton14.setText("Back");
        jButton14.setBorder(null);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setRequestFocusEnabled(false);
        jButton14.setVerifyInputWhenFocusTarget(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 350, -1));

        jButton8.setBackground(new java.awt.Color(152, 201, 45));
        jButton8.setFont(new java.awt.Font("Bookman Old Style", 0, 20)); // NOI18N
        jButton8.setForeground(new java.awt.Color(21, 25, 28));
        jButton8.setText("Forget Password");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 210, 40));

        jButton7.setBackground(new java.awt.Color(152, 201, 45));
        jButton7.setFont(new java.awt.Font("Bookman Old Style", 0, 20)); // NOI18N
        jButton7.setForeground(new java.awt.Color(21, 25, 28));
        jButton7.setText("Clear");
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 130, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 350, 10));

        result.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        result.setForeground(new java.awt.Color(255, 0, 0));
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 350, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 530));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 410, -1));

        jLabel20.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel20.setText("Password");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 260, -1));

        jButton15.setBackground(new java.awt.Color(169, 224, 49));
        jButton15.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jButton15.setText("Forget Password?");
        jButton15.setBorder(null);
        jButton15.setContentAreaFilled(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setRequestFocusEnabled(false);
        jButton15.setVerifyInputWhenFocusTarget(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 260, 30));

        jButton9.setBackground(new java.awt.Color(152, 201, 45));
        jButton9.setFont(new java.awt.Font("Bookman Old Style", 0, 20)); // NOI18N
        jButton9.setForeground(new java.awt.Color(21, 25, 28));
        jButton9.setText("Sign In");
        jButton9.setBorder(null);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 120, 40));

        jButton12.setBackground(new java.awt.Color(152, 201, 45));
        jButton12.setFont(new java.awt.Font("Bookman Old Style", 0, 20)); // NOI18N
        jButton12.setForeground(new java.awt.Color(21, 25, 28));
        jButton12.setText("Clear");
        jButton12.setBorder(null);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setFocusPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 130, 40));

        Passerror.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Passerror.setForeground(new java.awt.Color(255, 0, 0));
        Passerror.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(Passerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 260, 20));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transfer.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 40));

        jLabel22.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel22.setText("Select User");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 260, -1));

        Selecterror.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Selecterror.setForeground(new java.awt.Color(255, 0, 0));
        Selecterror.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(Selecterror, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 260, 20));

        Usererror.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Usererror.setForeground(new java.awt.Color(255, 0, 0));
        Usererror.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(Usererror, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 260, 20));

        SelectUser.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        SelectUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User", "Admin" }));
        SelectUser.setAutoscrolls(true);
        SelectUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SelectUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectUserMouseClicked(evt);
            }
        });
        jPanel1.add(SelectUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 260, 40));

        timeshow.setFont(new java.awt.Font("Bookman Old Style", 0, 16)); // NOI18N
        timeshow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(timeshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 350, 30));
        Timer timer;
        ActionListener actionListener = new ActionListener(){
            public void actionPerformed(ActionEvent e){
                Date date = new Date();
                DateFormat timeFormat = new SimpleDateFormat("EEEE, d MMMM yyyy hh:mm:ss:aa");
                String times = timeFormat.format(date);
                timeshow.setText(times);
            }
        };
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 350, 10));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 20, 530));

        jPasswordField_Password.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jPasswordField_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordField_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_PasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 260, 40));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 350, 10));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EXIT");
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 350, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_UserIDMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_UserIDMouseMoved

    }//GEN-LAST:event_jTextField_UserIDMouseMoved

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jPanel6.setVisible(false);
        jLabel_info_logo.setVisible(true);
        jLabel_info2.setVisible(true);
        jLabel_info1.setVisible(true);
        jPasswordField_Password.setEditable(true);
        jPasswordField_Password.setEnabled(true);
        ShowPassword.setEnabled(true);
        SelectSecurityQuestion.setSelectedItem("SELECT HERE");
        EnterSecurityAnswer.setText("");
        newpassword.setText("");
        confirmnewpassword.setText("");
        result.setText(""); 
        SelectUser.setSelectedItem("User");
        jTextField_UserID.setText("");
        jButton12.setEnabled(true);
        jButton9.setEnabled(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        SelectSecurityQuestion.setSelectedItem("SELECT HERE");
        EnterSecurityAnswer.setText("");
        newpassword.setText("");
        confirmnewpassword.setText("");
        result.setText("");
        SelectUser.setSelectedItem("Admin");
        jTextField_UserID.setText("");
        jPasswordField_Password.setText("");        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String usert=SelectUser.getSelectedItem().toString();
        if(usert=="Admin"){
            if(jTextField_UserID.getText().trim().isEmpty() && SelectSecurityQuestion.equals("SELECT HERE") && EnterSecurityAnswer.getText().trim().isEmpty() && newpassword.getText().trim().isEmpty() && confirmnewpassword.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields","Woops", JOptionPane.ERROR_MESSAGE);
            }
            else if(jTextField_UserID.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Empty field detected ! Please Enter Your UserID", "Woops", JOptionPane.ERROR_MESSAGE);
            }
            else if(SelectSecurityQuestion.getSelectedItem().toString().equals("SELECT HERE")){
                JOptionPane.showMessageDialog(null, "Wrong Selection ! Please Select Correct Security Question", "Woops", JOptionPane.ERROR_MESSAGE);
            }
            else if(EnterSecurityAnswer.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Empty field detected ! Please Enter Your Security Answer", "Woops", JOptionPane.ERROR_MESSAGE);
            }
            else if(newpassword.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Empty field detected ! Please Enter Your New Password", "Woops", JOptionPane.ERROR_MESSAGE);
            } 
            else if(confirmnewpassword.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Empty field detected ! Please Enter Your Confirm New Password", "Woops", JOptionPane.ERROR_MESSAGE);
            }
            else if(!Arrays.equals(newpassword.getPassword(), confirmnewpassword.getPassword())){           
                JOptionPane.showMessageDialog(null, "Password Mismatch.\nPlease ReEnter a Password.", "Woops", JOptionPane.ERROR_MESSAGE);
            }
            else{            
                try{
                    ImageIcon icon = new ImageIcon(getClass().getResource("/icons/tick.gif"));
                    String query = "select * from login where User_Id LIKE '"+jTextField_UserID.getText()+"'";
                    PreparedStatement statement = conn.prepareStatement(query);
                    ResultSet result = statement.executeQuery();
                    if (result.next()){
                        String SecQues=result.getString("Security_Question").toString().trim();
                        String SecAns=result.getString("Security_Answer").toString().trim();
                        String dbuser=result.getString("User_Id").toString().trim();
                        String name=result.getString("User_Name").toString().trim();
                        String EnterSecQues=SelectSecurityQuestion.getSelectedItem().toString().trim();
                        String EnteredSecAns=EnterSecurityAnswer.getText().trim();
                            if(SecQues.equals(EnterSecQues) && SecAns.equals(EnteredSecAns)){
                                String uppass= "update login set User_Password = '"+newpassword.getText()+"' where User_Id = '"+jTextField_UserID.getText()+"';";
                                PreparedStatement updatepass= conn.prepareStatement(uppass);
                                updatepass.executeUpdate();
                                
                                String usertask =( "Password Forget of this Admin:- "+jTextField_UserID.getText());
                                String userlog = "insert into history (sno, User_Id, User_Name, Date_Time, User_Task) values(null,'"+jTextField_UserID.getText()+"','"+name+"','"+timeshow.getText()+"','"+usertask+"')";
                                pst = conn.prepareStatement(userlog);
                                pst.executeUpdate();
                                
                                JOptionPane.showMessageDialog(null,"You have successfully updated your password...\nPlease Re-login again","Successfully Done", JOptionPane.INFORMATION_MESSAGE, icon);
                                Login l = new Login();
                                l.setVisible(true);
                                dispose();
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Wrong answer - Please Select a Correct Question.", "Woops", JOptionPane.ERROR_MESSAGE);
                                EnterSecurityAnswer.setText("");
                                newpassword.setText("");
                                confirmnewpassword.setText("");
                            }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Wrong Query", "Woops", JOptionPane.ERROR_MESSAGE);
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }                
            }                        
        }
        else{
            JOptionPane.showMessageDialog(null, "Only Admin can update Password.\nPlease contact from your ADMIN.", "Woops", JOptionPane.ERROR_MESSAGE);
            SelectUser.setSelectedItem("Admin");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void EnterSecurityAnswerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterSecurityAnswerMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterSecurityAnswerMouseMoved

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        SelectUser.setSelectedItem("Admin");
        jLabel_info_logo.setVisible(false);
        jLabel_info2.setVisible(false);
        jLabel_info1.setVisible(false);
        jPanel6.setVisible(true);
        jTextField_UserID.setText("");
        jPasswordField_Password.setText("");
        jPasswordField_Password.setEditable(false);
        jPasswordField_Password.setEnabled(false);
        ShowPassword.setEnabled(false);
        jButton12.setEnabled(false);
        jButton9.setEnabled(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
/*        if(jTextField_UserID.getText().trim().isEmpty() && jPasswordField_Password.getText().trim().isEmpty()){
            Usererror.setText("Enter Username");
            Passerror.setText("Enter Password");
            JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields", "Woops", JOptionPane.ERROR_MESSAGE);

        }
        else if(jTextField_UserID.getText().trim().isEmpty()){
            Usererror.setText("Enter Username");
            Passerror.setText("");
            JOptionPane.showMessageDialog(null, "Empty field detected ! Please fill up UserID", "Woops", JOptionPane.ERROR_MESSAGE);
        }
        else if(jPasswordField_Password.getText().trim().isEmpty()){
            Usererror.setText("");
            Passerror.setText("Enter Password");
            JOptionPane.showMessageDialog(null, "Empty field detected ! Please fill up Password", "Woops", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String sql = "select * from login where User_Id LIKE '"+jTextField_UserID.getText()+"'";
            try {
                pst = conn.prepareStatement(sql);
                rs=pst.executeQuery();
                String user = jTextField_UserID.getText();
                String pwd = new String (jPasswordField_Password.getPassword());
                String type =(String)SelectUser.getSelectedItem();
                while(rs.next()) { 
                    String uname = rs.getString("User_Id");
                    String pass = rs.getString("User_Password");
                    String name = rs.getString("User_Name");
                    String lastlogin=rs.getString("User_Last_login").toString().trim();
                    String utype = rs.getString("User_Type");
                    if ((user.equals(uname)) && (pwd.equals(pass) && utype.equals(type))) { 
                        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/tick.gif"));
                        if (type.equals("Admin")) { 
                            JOptionPane.showMessageDialog(null,"You have successfully logged in.\nYour Last Login is :- "+lastlogin,"Welcome :- "+name, JOptionPane.INFORMATION_MESSAGE, icon);
                            String Lastlogin= "update login set User_Last_login = '"+timeshow.getText()+"' where User_Id = '"+jTextField_UserID.getText()+"'";
                            PreparedStatement updatelastlogin= conn.prepareStatement(Lastlogin);
                            updatelastlogin.executeUpdate();
                            String info[]=new String[2];
                            info[0]=uname;
                            info[1]=name;
                            Admin_Dashboard.main(info);
                            this.setVisible(false);                                
                        } 
                        else if (type.equals("User")) {
                            JOptionPane.showMessageDialog(null,"You have successfully logged in.\nYour Last Login is :- "+lastlogin,"Welcome :- "+name, JOptionPane.INFORMATION_MESSAGE, icon);                            
                            String Lastlogin= "update login set User_Last_login = '"+timeshow.getText()+"' where User_Id = '"+jTextField_UserID.getText()+"'";
                            PreparedStatement updatelastlogin= conn.prepareStatement(Lastlogin);
                            updatelastlogin.executeUpdate();
                            String info[]=new String[2];
                            info[0]=uname;
                            info[1]=name;
                            Dashboard.main(info);
                            this.setVisible(false);
                        }
                        else{
                            JOptionPane.showMessageDialog(null,  "User ID does not match!","ALERT!", JOptionPane.ERROR_MESSAGE); 
                            break;                            
                        }
                    } 
                    else {
                        JOptionPane.showMessageDialog(null,  "Password does not match!","ALERT!", JOptionPane.ERROR_MESSAGE); 
                        break;
                    }
                }
              } 
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }              
        } */
        if(jTextField_UserID.getText().trim().isEmpty() && jPasswordField_Password.getText().trim().isEmpty()){
            Usererror.setText("Enter Username");
            Passerror.setText("Enter Password");
            JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields", "Woops", JOptionPane.ERROR_MESSAGE);
        }else if(jTextField_UserID.getText().trim().isEmpty()){
            Usererror.setText("Enter Username");
            Passerror.setText("");
            JOptionPane.showMessageDialog(null, "Empty field detected ! Please fill up UserID", "Woops", JOptionPane.ERROR_MESSAGE);
        }else if(jPasswordField_Password.getText().trim().isEmpty()){
            Usererror.setText("");
            Passerror.setText("Enter Password");
            JOptionPane.showMessageDialog(null, "Empty field detected ! Please fill up Password", "Woops", JOptionPane.ERROR_MESSAGE);
        }else{
            String sql = "select * from login where User_Id LIKE '"+jTextField_UserID.getText()+"'";
            try {
                pst = conn.prepareStatement(sql);
                rs=pst.executeQuery();
                String user = jTextField_UserID.getText();
                String pwd = new String (jPasswordField_Password.getPassword());
                String type =(String)SelectUser.getSelectedItem();
                while(rs.next()) { 
                    String uname = rs.getString("User_Id");
                    String pass = rs.getString("User_Password");
                    String name = rs.getString("User_Name");
                    String lastlogin=rs.getString("User_Last_login").toString().trim();
                    String utype = rs.getString("User_Type");
                    if (user.equals(uname) && utype.equals(type)){
			if(pwd.equals(pass)){ 
                                ImageIcon icon = new ImageIcon(getClass().getResource("/icons/tick.gif"));
                                if (type.equals("Admin")) { 
                                    JOptionPane.showMessageDialog(null,"You have successfully logged in.\nYour Last Login is :- "+lastlogin,"Welcome :- "+name, JOptionPane.INFORMATION_MESSAGE, icon);
                                    String Lastlogin= "update login set User_Last_login = '"+timeshow.getText()+"' where User_Id = '"+jTextField_UserID.getText()+"'";
                                    PreparedStatement updatelastlogin= conn.prepareStatement(Lastlogin);
                                    updatelastlogin.executeUpdate();
                                    
                                    String admintask =( "LogIn By This Admin:- "+jTextField_UserID.getText()+" "+name);
                                    String useradmin = "insert into history (sno, User_Id, User_Name, Date_Time, User_Task) values(null,'"+uname+"','"+name+"','"+timeshow.getText()+"','"+admintask+"')";
                                    pst = conn.prepareStatement(useradmin);
                                    pst.executeUpdate();
                                    
                                    String info[]=new String[2];
                                    info[0]=uname;
                                    info[1]=name;
                                    Admin_Dashboard.main(info);
                                    this.setVisible(false);                                
                                } 
                                else if (type.equals("User")) {
                                    JOptionPane.showMessageDialog(null,"You have successfully logged in.\nYour Last Login is :- "+lastlogin,"Welcome :- "+name, JOptionPane.INFORMATION_MESSAGE, icon);                            
                                    String Lastlogin= "update login set User_Last_login = '"+timeshow.getText()+"' where User_Id = '"+jTextField_UserID.getText()+"'";
                                    PreparedStatement updatelastlogin= conn.prepareStatement(Lastlogin);
                                    updatelastlogin.executeUpdate();
                                    
                                    String usertask =( "LogIn By This User:- "+jTextField_UserID.getText()+" "+name);
                                    String userlog = "insert into history (sno, User_Id, User_Name, Date_Time, User_Task) values(null,'"+uname+"','"+name+"','"+timeshow.getText()+"','"+usertask+"')";
                                    pst = conn.prepareStatement(userlog);
                                    pst.executeUpdate();
                                    
                                    String info[]=new String[2];
                                    info[0]=uname;
                                    info[1]=name;
                                    Dashboard.main(info);
                                    this.setVisible(false);
                                }else{
                                    JOptionPane.showMessageDialog(null,  "User ID does not match!","ALERT!", JOptionPane.ERROR_MESSAGE); 
                                    break;                            
                                }
                            }else {
                        JOptionPane.showMessageDialog(null,  "Password does not match!","ALERT!", JOptionPane.ERROR_MESSAGE); 
                        break;
                        }
                    }else {
                        JOptionPane.showMessageDialog(null,  "User ID does not match!","ALERT!", JOptionPane.ERROR_MESSAGE); 
                        break;
                    }
                }
            }catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }              
        }  
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        SelectUser.setSelectedItem("User");
        jTextField_UserID.setText("");
        jPasswordField_Password.setText("");
        Passerror.setText("");
        Usererror.setText("");
        Selecterror.setText("");
        
        jPanel6.setVisible(false);
        jLabel_info_logo.setVisible(true);
        jLabel_info2.setVisible(true);
        jLabel_info1.setVisible(true);
        jPasswordField_Password.setEditable(true);
        jPasswordField_Password.setEnabled(true);
        ShowPassword.setEnabled(true); 
        
        SelectSecurityQuestion.setSelectedItem("What was the name of the company where you first worked?");
        EnterSecurityAnswer.setText("");
        newpassword.setText("");
        confirmnewpassword.setText("");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField_UserIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_UserIDKeyPressed
        // TODO add your handling code here:
        Usererror.setText("");
    }//GEN-LAST:event_jTextField_UserIDKeyPressed

    private void confirmnewpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmnewpasswordKeyPressed
        // TODO add your handling code here:
       /*String password1=Arrays.toString(newpassword.getPassword());
        String password2=Arrays.toString(confirmnewpassword.getPassword());*/

        String password1=newpassword.getPassword().toString();
        String password2=confirmnewpassword.getPassword().toString();
        if(password1 == password2) {
            result.setText("Passwords do not match");
        }
        else {
            result.setText("");
        }
        /*if (!Arrays.equals(newpassword.getPassword(), confirmnewpassword.getPassword())) {
   JOptionPane.showMessageDialog(null, "Passwords do not match.", "Woops", JOptionPane.ERROR_MESSAGE);
} */
    }//GEN-LAST:event_confirmnewpasswordKeyPressed

    private void SelectUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectUserMouseClicked
        // TODO add your handling code here:
        Selecterror.setText("");
    }//GEN-LAST:event_SelectUserMouseClicked

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        // TODO add your handling code here:
        if(ShowPassword.isSelected()){
            jPasswordField_Password.setEchoChar((char)0);
        }
        else{
            jPasswordField_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPasswordActionPerformed

    private void jPasswordField_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordKeyPressed
        // TODO add your handling code here:
        Passerror.setText("");
    }//GEN-LAST:event_jPasswordField_PasswordKeyPressed

    private void newpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newpasswordKeyPressed
        // TODO add your handling code here:
        confirmnewpassword.setText("");
        result.setText("");
    }//GEN-LAST:event_newpasswordKeyPressed

    private void ForgetShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgetShowPasswordActionPerformed
        // TODO add your handling code here:
        if(ForgetShowPassword.isSelected()){
            newpassword.setEchoChar((char)0);
        }
        else{
            newpassword.setEchoChar('*');
        }        
    }//GEN-LAST:event_ForgetShowPasswordActionPerformed

    private void confirmnewpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmnewpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmnewpasswordActionPerformed

    private void ForgetConfirmShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgetConfirmShowPasswordActionPerformed
        // TODO add your handling code here:
        if(ForgetConfirmShowPassword.isSelected()){
            confirmnewpassword.setEchoChar((char)0);
        }
        else{
            confirmnewpassword.setEchoChar('*');
        }        
    }//GEN-LAST:event_ForgetConfirmShowPasswordActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/tick.gif"));        
        JOptionPane.showMessageDialog(null,"Project Submitted By :- \nName :- \t HARJOT SINGH - 10571723829\n \t                AMIT KUMAR      - 10571723843"
                + "\nClass :- B.Sc. (Information Technology), Semester - VI","GREEN GLOBAL :- STOCK MANAGEMENT SYSTEM", JOptionPane.INFORMATION_MESSAGE, icon);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel_info_logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_info_logoMouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/tick.gif"));        
        JOptionPane.showMessageDialog(null,"Project Submitted By :- \nName :- \t HARJOT SINGH - 10571723829\n \t                AMIT KUMAR      - 10571723843"
                + "\nClass :- B.Sc. (Information Technology), Semester - VI","GREEN GLOBAL :- STOCK MANAGEMENT SYSTEM", JOptionPane.INFORMATION_MESSAGE, icon);        
    }//GEN-LAST:event_jLabel_info_logoMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        /*try{
            File file =new File ("C:\\xampp\\xampp_stop.exe");
            if(file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }else{
                    JOptionPane.showMessageDialog(null,"Not Supperted");
                }
            }else{
                JOptionPane.showMessageDialog(null, "File Not Exist");
            }
        }catch(Exception e){
            e.printStackTrace();
        }*/
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EnterSecurityAnswer;
    private javax.swing.JToggleButton ForgetConfirmShowPassword;
    private javax.swing.JToggleButton ForgetShowPassword;
    private javax.swing.JLabel Passerror;
    private javax.swing.JComboBox<String> SelectSecurityQuestion;
    private javax.swing.JComboBox<String> SelectUser;
    private javax.swing.JLabel Selecterror;
    private javax.swing.JToggleButton ShowPassword;
    private javax.swing.JLabel Usererror;
    private javax.swing.JPasswordField confirmnewpassword;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_info1;
    private javax.swing.JLabel jLabel_info2;
    private javax.swing.JLabel jLabel_info_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField_UserID;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JLabel result;
    private javax.swing.JLabel timeshow;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/trending 512.png")));
    }
}
